spring:
  security:
    user:
      name: admin
      password: 123
      roles: ADMIN
  devtools:
    livereload:
      enabled: false
    restart:
      enabled: false

server:
  servlet:
    session:
      timeout: 10 

  jpa:
    hibernate:
      open-in-view: false
      ddl-auto: create
    properties:
      hibernate:
        default_batch_fetch_size: 1000
        show_sql: true
        format_sql: true
