spring:
  # security:
  #   user:
  #     name: admin
  #     password: 123
  #     roles: ADMIN
  #   oauth2:
  #     client:
  #       registration:
  #         google:
  #           client-id: 234310243630-b8h8hshhor5qvsuviol64paoco5mq40i.apps.googleusercontent.com
  #           client-secret: rWIEYaXge4zPHmaeGaEDpr4h
  datasource:
    url: jdbc:h2:tcp://localhost/C:\data\spring-security
    username: sa
    password:
    driver-class-name: org.h2.Driver
  devtools:
    livereload:
      enabled: false
    restart:
      enabled: false

debug: true

server:
  servlet:
    session:
      timeout: 10 

  jpa:
    hibernate:
      open-in-view: false
      ddl-auto: create
    properties:
      hibernate:
        default_batch_fetch_size: 1000
        show_sql: true
        format_sql: true
